### ISSUE TITLE
Docs on config setup

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/blueapi#532]
That would be good as well, but I think having examples in the docs without having to read through the code would be helpful for setting up new environments.

_Originally posted by @tpoliaw in https://github.com/DiamondLightSource/blueapi/pull/408#issuecomment-2199487149_

**Comment by callumforrester** [comment]
@stan-dot could you add more description/context to this issue please?

**Comment by callumforrester** [comment]
This has been done in the dodal and ophyd-async documentation. I think we should close this issue, or at most just include links in the blueapi docs.

**Comment by stan-dot** [comment]
what do you think @tpoliaw ?

**Comment by tpoliaw** [comment]
I still think there needs to be something prominent in the docs/ getting started that details what should go in the config file. It [currently says](https://diamondlightsource.github.io/blueapi/main/how-to/configure-app.html) use  `blueapi --config path/to/file.yaml` to pass configuration but not what should go in the file, only that "An example of this yaml file is found in `config/defaults.yaml`" which no longer exists.

**Comment by callumforrester** [comment]
...true, reading your original comment, I think the title of this issue may just be wrong. @stan-dot could you rename it to be about the blueapi config, rather than ophyd-async devices?

**Comment by stan-dot** [comment]
I think to add 
```
env:
  sources:
    - kind: dodal
      module: dodal.beamlines.p38
    - kind: planFunctions
      module: dls_bluesky_core.plans
    - kind: planFunctions
      module: dls_bluesky_core.stubs
  data_writing:
    visit_directory: /dls/p38/data/2023/cm33874-1
    group_name: BL38P

```

to `blueapi.config.ConfigLoader`  as docstring. What do you think @tpoliaw  , @callumforrester ?
