### ISSUE TITLE
Need to provide scratch root twice in `values.yaml`

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/blueapi#646]
From testing on i04 it was found that to get `blueapi` to pick up the scratch directory it had to be provided in `worker` and in `initContainer` e.g.
```
worker:
  stomp:
    host: i04-control.diamond.ac.uk
  env:
    events:
      broadcast_status_events: False
    sources:
      - kind: dodal
        module: dodal.beamlines.i04
      - kind: planFunctions
        module: mx_bluesky.beamlines.i04
  scratch:
    root: /blueapi-plugins/scratch
initContainer:
  scratch:
    root: /blueapi-plugins/scratch
    repositories:
      - name: "dodal"
        remote_url: https://github.com/DiamondLightSource/dodal.git
      - name: "mx_bluesky"
        remote_url: https://github.com/DiamondLightSource/mx_bluesky.git
scratchHostPath: /dls_sw/i04/software/bluesky/scratch
```
This is annoying redundancy but worse is that it does not match the example given in https://github.com/DiamondLightSource/blueapi/blob/main/helm/blueapi/values.yaml

## Acceptance Criteria
* At least, the example is update to say match what is required
* Ideally I only need to provide the path once
