### ISSUE TITLE
in openapi.yaml the OperationId field is confusing

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/blueapi#833]
when I look at the openapi.yaml file I see
`operationId: get_devices_devices_get`

```yaml
  /devices/{name}:
    get:
      description: Retrieve information about a devices by its (unique) name.
      operationId: get_device_by_name_devices__name__get
```
I'd rather see `get_devices` and `get_device_by_name`

## Acceptance Criteria
- the operationId is normal
