### ISSUE TITLE
Environment varaible substitution in config

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#847]
As a user I would like to use environment variables when configuring blueapi, for example I would like to supply the following config for the CLI:

```yaml
stomp:
  auth:
    username: guest
    password: guest
  host: ${BEAMLINE}-rabbitmq.diamond.ac.uk
oidc:
  well_known_url: "https://authn.diamond.ac.uk/realms/master/.well-known/openid-configuration"
  client_id: blueapi-cli
api:
  host: ${BEAMLINE}-blueapi.diamond.ac.uk
  port: 80
logging:
  level: ERROR
```

## Acceptance Criteria
- `${BEAMLINE}` resolves to `${BEAMLINE}`'s value in the above case
- Tests prove that environment variables resolve
