### ISSUE TITLE
Splitting URLs in config is hard to debug

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/blueapi#985]
As a support engineer I find it easy to forget to configure some part of the url when the config is structured, for example:

```yaml
api: 
  host: my-beamline-blueapi.diamond.ac.uk
  port: 443
  protocol: https
```

All 3 need to be present for it to work, it is easy to forget one.

## Steps To Reproduce
1. Remove any one of the example lines above
2. Try to perform a request against a production blueapi machine

## Proposed Solution

Move to text urls in the config, e.g. the above changes to

```yaml
api:
  url: https://my-beamline-blueapi.diamond.ac.uk/
```

## Acceptance Criteria
- Structured config is replaced with URL strings for the following
  - `api`
  - `stomp`
- Unit tests fixed
